# Changes here will be overwritten by Copier
_commit: v0.8.5
_src_path: gh:larsrollik/templatepy
author_email: l.b.rollik@protonmail.com
author_name: Lars B. Rollik
github_repo: ttl-barcoder
github_username: murineshiftwork
license_type: noncommercial
private_repo_deps: false
project_description: TTL barcode generation for multi-system DAQ synchronization
project_name: ttl-barcoder
project_slug: ttl_barcoder
python_requires: '3.10'
year: '2024'
